### PR TITLE
Improve user controls.

### PR DESCRIPTION
**Pull request by RadostW**
Before this pull request:
[ESC] - does nothing
[CTRL+DRAG] - does nothing
[SHIFT+ARROW] - does nothing

After this pull request:
[ESC] - does back action
[CTRL+DRAG] - pans around
[SHIFT+ARROW] - pans arond
no other action is changed

Rationale:
[ESC] key does not do what many users (most) users expect it should do, and is the first thing users press when they accidentally click in the drawing pane.
Currently 'back' action is mapped to [CTRL+BACKSPACE] -- very esotheric. An additional hotkey [ESC] is added.

Similarly [ALT+DRAG] is rarely used in other applications. Additional key combination of [CTRL+DRAG] is added.

Keyboard navigation is a standard. Hardly anyone has a numpad these days. [SHIFT+ARROW] leaves [ARROW] alone for (moving inside menus works like it used to).

### CODE REVIEW

**Comment by goatchurchprime** [comment]
Hot dang! I completely missed seeing this PR, having not been monitoring this repo enough.

I found it just as I was attempting to put a version of it into Nixos: https://github.com/NixOS/nixpkgs/pull/239739

I wonder if it's possible to get all the rest of the cave drawing software in the world installing and running under nix, even if some of them can only be made to work through wine64.

**Comment by RadostW** [comment]
Does this conflict with the updates I have proposed? It seems to me that there are no conflicts with the base branch.

**Comment by goatchurchprime** [comment]
No it doesn't.  The changes are good.  It's just in sort of a feature freeze during the process of nixifying. As I said, I regret not seeing this PR months ago. But I'll deal with it and a bunch of other annoyances that are now visible when is runs within the nix system.

**Comment by goatchurchprime** [comment]
Looks great.

I'm now getting to do some of this stuff, after having got it into nixpkgs.

  https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/gis/tunnelx/default.nix#L49

**Comment by goatchurchprime** [comment]
I did find a snag with one of the changes -- the one that let CTRL left mouse click drag the window, as it prevents starting and stopping a path on a node

https://github.com/CaveSurveying/tunnelx/blob/20af3f82808115d76c53e6ed98355e1772a81850/src/SketchGraphics.java#L2714

**Pull request merged**
